
CREATE TABLE ITEM(
  ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(255),
  PRICE INT,
  DTYPE VARCHAR(6)
);

CREATE TABLE ALBUM(
    ITEM_ID BIGINT PRIMARY KEY,
    ARTIST VARCHAR(255),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

CREATE TABLE MOVIE(
    ITEM_ID BIGINT PRIMARY KEY,
    DIRECTOR VARCHAR(255),
    ACTOR VARCHAR(255),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

CREATE TABLE BOOK(
   ITEM_ID BIGINT PRIMARY KEY,
   AUTHOR VARCHAR(255),
   ISBN VARCHAR(255),
   FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);
